FROM nvidia/cuda:11.4.1-devel-ubuntu20.04

WORKDIR /workspace

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update; exit 0
# install common tool
RUN apt-get install -y tar xz-utils vim
# install python
RUN apt-get install -y python3 python3-pip
# install blender shared library
RUN apt-get install -y \
    libx11-6 \
    libxi6 \
    libxxf86vm1 \
    libxfixes3 \
    libxrender1 \
    libgl1 \
    libglib2.0-0 \
    libfreetype6 \
    libgl1-mesa-dev \
    libglu1-mesa

# install Blender
COPY blender-2.92.0-linux64.tar.xz .
RUN tar xvf blender-2.92.0-linux64.tar.xz
RUN rm blender-2.92.0-linux64.tar.xz
RUN ln -s /workspace/blender-2.92.0-linux64/blender /usr/bin/blender

# install BlenderFunc
COPY blenderfunc.tar.xz .
RUN mkdir blenderfunc
RUN tar xvf blenderfunc.tar.xz -C blenderfunc
RUN rm blenderfunc.tar.xz

# change to normal user
RUN groupadd -r general && useradd -r -g general general
RUN chown -R general:general /workspace && chmod 755 /workspace
RUN mkdir /home/general && chown -R general:general /home/general && chmod 755 /home/general
USER general
WORKDIR /workspace/blenderfunc

# use tsinghua pypi source
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN blender --background --python examples/helloworld.py
